language: php
php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0
before_install:
    - cp app/config/parameters.yml.dist app/config/parameters.yml
install:
    - npm install -g grunt-cli
    - npm install -g bower
    - npm install || true
    - bower install
    - composer install -n
script: grunt verification
branches:
    only:
        - master
